services:
  wordpress:
    image: wordpress:6.6.2-apache
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-data:/var/www/html
  db:
    image: mysql:9.0.1
    container_name: wordpressdb
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db-data:/var/lib/mysql
