services:
  db:
    image: mysql:5.7   # Recommended stable MySQL version by Wordpress
    container_name: wordpress_db
    volumes:
      - /mnt/wordpress-db:/var/lib/mysql # Mount the block storage volume
    networks:
      - wp_net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8080:80"       # Expose port 8080 on your Lightsail instance to access WordPress
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - wp_net
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

volumes:
  db_data:    # Persistent volume for MySQL data
  wp_data:    # Persistent volume for WordPress data

networks:
  wp_net:

